:runtime src/global_constant.vim
:runtime src/settings.vim
:runtime src/functions/index.vim
:runtime src/autocmd.vim
:runtime src/vim-plug.vim
:runtime src/packer.lua
:runtime src/plugin-config.vim
:runtime src/plugin-config.lua
:runtime src/theme-config.vim
:runtime src/commands.vim
:runtime src/hot-key.vim
:runtime src/other.vim
