:runtime src/global_constant.vim
:runtime src/functions.vim
:runtime src/settings.vim
:runtime src/plugin-loader.vim
:runtime src/plugin-config.vim
:runtime src/theme-config.vim
:runtime src/format.vim
:runtime src/commands.vim
:runtime src/hot-key.vim
:runtime src/other.vim
