runtime src/functions/dialog.lua
runtime src/functions/ctags.lua
runtime src/functions/format.lua
runtime src/functions/row.vim
runtime src/functions/hot-key.vim
runtime src/functions/template.lua
runtime src/functions/other.vim
runtime src/functions/util.lua
runtime src/functions/cmake.lua
