command! LoadCtags call LoadCtags()
command! UpdateCtags call UpdateCtags()
command! FileFormat call FileFormat()
command! -nargs=1 TemplateNew lua TemplateNew(<args>)
command! TemplateList lua TemplateList()
command! -nargs=1 TemplateUse lua TemplateUse(<args>)
command! -nargs=1 TemplateDelete lua TemplateDelete(<args>)
